Remaining Doctype Errors
HTMLParseErrorWG/parse5 pull request #10
Opened 2017-04-22 09:19 UTC by diervo

@inikulin Let me know if the names make sense to you.

2017-04-24 09:12 UTC, inikulin requested changes

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.missingSeparationCharacterInDoctype);
It's better be named `missing-whitespace-after-doctype-public-keyword`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.missingSeparationCharacterInDoctype);
Same as above

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
We've used term `abrupt` previously for such cases, so it's an `abrupt-closing-of-doctype`.

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
It's `missing-quote-around-doctype-public-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
`missing-quote-before-doctype-public-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.missingSeparationCharacterInDoctype);
`missing-whitespace-after-doctype-public-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.missingSeparationCharacterInDoctype);
`missing-whitespace-between-doctype-public-and-system-identifiers`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
`missing-quote-before-doctype-system-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
`missing-quote-before-doctype-system-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.missingSeparationCharacterInDoctype);
`missing-whitespace-after-doctype-system-keyword`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.missingSeparationCharacterInDoctype);
`missing-whitespace-after-doctype-system-keyword`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
`missing-quote-before-doctype-system-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
`missing-quote-before-doctype-system-identifier`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedClosingOfDoctype);
`abrupt-closing-of-doctype`

2017-04-24 09:12 UTC, inikulin commented on lib/tokenizer/index.js
> +        this._err(ERR.unexpectedCharacterInDoctype);
`unexpected-character-after-doctype-system-identifier`

2017-04-24 15:36 UTC, diervo commented
@inikulin You just keep on not liking my spanglish errors names! xD
Great, I knew you would have good feedback for the names, will change them and push the changes on the rest of repos.

2017-04-24 19:42 UTC, inikulin commented
@diervo

> You just keep on not liking my spanglish errors names!

Nah, I just replace them with russinglish variants :D

2017-05-01 05:15 UTC, diervo commented
//cc @inikulin had to rebase, but everything ready for the almost last merge.

2017-05-10 06:34 UTC, diervo commented
@inikulin Only the last renames are missing, I will try to finish this + tests tomorrow for sure.

2017-05-11 06:10 UTC, diervo commented
@inikulin rebased and ready to merge

2017-05-11 08:36 UTC, inikulin requested changes

2017-05-11 08:36 UTC, inikulin commented on lib/common/error_codes.js
> +    missingQuoteAroundDoctypePublicIdentifier: 'missing-quote-around-doctype-public-identifier',
`missingQuoteAroundDoctypePublicIdentifier` is not used anymore

2017-05-11 08:36 UTC, inikulin commented on lib/common/error_codes.js
> +    controlOrUndefinedCharacterReference: 'control-or-undefined-character-reference',
Seems like a rebase artefact. This one is not used anymore.

2017-05-11 09:14 UTC, inikulin commented
@diervo I guess I'll merge it as is and fix those minor issues. Congratulations! We've done with first huge chunk of work.

2017-05-11 09:14 UTC, merged